name: Deploy to GCP

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ${{ secrets.GCP_DEPLOY_PATH }}
            sudo chown -R ${{ secrets.GCP_USER }}:${{ secrets.GCP_USER }} .
            git reset --hard HEAD
            # git config --global --add safe.directory ${{ secrets.GCP_DEPLOY_PATH }}
            git pull origin master
            npm install
            npm run build
            sudo pm2 restart visit-card || sudo pm2 start build --name visit-card
            sudo chown -R ${{ secrets.GCP_ROOT_USER }}:${{ secrets.GCP_ROOT_USER }} .
